# Generated by Django 3.1.3 on 2021-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='if_other_specify',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='operation_date',
            field=models.DateField(verbose_name='Date of Operation'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='species_operated_on',
            field=models.CharField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20, verbose_name='Animal species affected'),
        ),
    ]
