# Generated by Django 3.1.3 on 2021-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_consultation',
            name='by_veterinary_officer',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=20, verbose_name='Is the farm manged by a veterinary officer or livestock officer?'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='culling_selection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Culling and Selection.'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disease control.'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='farm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Farm biosecurity'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='grazing',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Grazing system and pasture management.'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='if_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='If no,who is the farm consultant?'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='name_incharge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the veterinary officer incharge.'),
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='reg_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration number.'),
        ),
    ]
