# Generated by Django 3.1.3 on 2021-03-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sick_approach_form',
            name='id',
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='vet_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms'),
        ),
    ]
