# Generated by Django 3.1.3 on 2021-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death_approach_form',
            name='death_time',
            field=models.DateField(verbose_name='At what time the animal the animals died'),
        ),
    ]
