# Generated by Django 3.1.3 on 2021-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgical_approach_form',
            old_name='post_operation_management',
            new_name='post_management',
        ),
        migrations.RemoveField(
            model_name='surgical_approach_form',
            name='name_of_the_animal',
        ),
        migrations.RemoveField(
            model_name='surgical_approach_form',
            name='species_operated_on',
        ),
        migrations.AddField(
            model_name='surgical_approach_form',
            name='species_affected',
            field=models.CharField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20, verbose_name='Animal species affected'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='case_history',
            field=models.CharField(max_length=100, verbose_name='When was the case reported'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='mortality_rate',
            field=models.CharField(max_length=100, verbose_name='State the mortality rate of the case reported'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='if_other_specify',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='If other,specify.'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='operation_date',
            field=models.DateField(verbose_name='Date of operation'),
        ),
    ]
