# Generated by Django 3.1.3 on 2021-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210318_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancy_diagnosis_form',
            name='if_positive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='If the result is positive give the approximate age of the fetus.'),
        ),
        migrations.AlterField(
            model_name='pregnancy_diagnosis_form',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='pregnancy_diagnosis_form',
            name='cow_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name or idenfication number of the cow'),
        ),
        migrations.AlterField(
            model_name='pregnancy_diagnosis_form',
            name='date_of_pregnancy_diagnosis',
            field=models.DateField(verbose_name='date of pregnancy diagnosis'),
        ),
    ]
