# Generated by Django 3.1.3 on 2021-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210313_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet_forms',
            name='vet_username',
            field=models.CharField(max_length=20),
        ),
    ]
