# Generated by Django 3.1.3 on 2021-04-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210401_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deworming_form',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Number of adults'),
        ),
    ]
