# Generated by Django 3.1.3 on 2021-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210226_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock_inventory_form',
            name='Attach_photos_of_your_animal',
            field=models.ImageField(upload_to='vet_photos', verbose_name='Upload photos'),
        ),
    ]
