# Generated by Django 3.1.3 on 2021-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210311_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deworming_form',
            name='date_of_deworming',
            field=models.DateField(verbose_name='Date of deworming'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='withdrawal_period',
            field=models.DurationField(verbose_name='withdrawal period'),
        ),
        migrations.AlterField(
            model_name='vaccination_form',
            name='date_of_vaccination',
            field=models.DateField(verbose_name='Date of vaccination'),
        ),
        migrations.AlterField(
            model_name='vaccination_form',
            name='next_date_of_vaccination',
            field=models.DateField(verbose_name='Next date of vaccination'),
        ),
    ]
