# Generated by Django 3.1.3 on 2021-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20210203_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death_approach_form',
            name='case_history',
            field=models.CharField(default='', max_length=100),
        ),
    ]
