# Generated by Django 3.1.3 on 2021-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20210401_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='operation_nature',
            field=models.CharField(choices=[('C', 'c_section'), ('I', 'interstinal_torsion'), ('T', 'tumor_extraction'), ('C', 'canine_spaying'), ('H', 'hernia'), ('W', 'Warts_extraction'), ('C', 'castration'), ('S', 'skin_injuries'), ('F', 'fructure'), ('R', 'rumenatomy'), ('O', 'other')], default='C', max_length=20, verbose_name='Nature of operation'),
        ),
    ]
