# Generated by Django 3.1.3 on 2021-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_auto_20210203_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='sex_of_the_animal',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='', max_length=20, verbose_name='Sex of the animal'),
        ),
    ]
