# Generated by Django 3.1.3 on 2021-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_auto_20210322_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificial_insemination_form',
            name='sire_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sire`s name'),
        ),
        migrations.AlterField(
            model_name='artificial_insemination_form',
            name='sire_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sire origin'),
        ),
    ]
