# Generated by Django 3.1.3 on 2021-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_auto_20210203_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock_inventory_form',
            name='Attach_photos_of_your_animal',
            field=models.ImageField(default='default.jpg', upload_to='vet_photos', verbose_name='Upload photos'),
        ),
    ]
