# Generated by Django 3.1.3 on 2021-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_auto_20210417_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death_approach_form',
            name='carcass_opened_for_the_pm',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=5, null=True, verbose_name='Did you open up the carcass fo PM?'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='case_history',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='death_cause_notifiable',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=5, null=True, verbose_name='Is the cause of dead notifiable?'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date the animal died'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='death_time',
            field=models.TimeField(blank=True, null=True, verbose_name='At what time the animal the animals died'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='mortality_rate',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='num_of_species_dead',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of animals dead'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='sex_of_the_animal',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], default='', max_length=20, null=True, verbose_name='Sex of the animal'),
        ),
        migrations.AlterField(
            model_name='death_approach_form',
            name='signs_of_cadever_on_the_ground',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What are the signs of signs of the cadever on the ground'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='body_condition_of_the_animal',
            field=models.CharField(blank=True, choices=[('G', 'good'), ('F', 'fair'), ('P', 'poor')], default='G', max_length=20, null=True, verbose_name='Body condition of the animal(s)'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='drug_choices',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Drug of choice'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='number_of_adults',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of adults'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='number_of_young_ones',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of young ones'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='species_targeted',
            field=models.CharField(blank=True, choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20, null=True, verbose_name='Species targetted'),
        ),
        migrations.AlterField(
            model_name='deworming_form',
            name='withdrawal_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livestock_inventory_form',
            name='Attach_photos_of_your_animal',
            field=models.ImageField(default='default.jpg', upload_to='livestock_pics', verbose_name='Upload photos'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='disease_diagnosis',
            field=models.CharField(blank=True, choices=[('C', 'clinical_signs'), ('L', 'laboratory')], default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='disease_nature',
            field=models.CharField(blank=True, choices=[('A', 'acute'), ('S', 'sub_acute')], default='0', max_length=20, null=True, verbose_name='nature of the disease'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='disease_one_of_the_zoonotic',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'no')], default='0', max_length=5, null=True, verbose_name='is the disease one of the zoonotic?'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='final_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='harmony_with_clinic_signs_and_lab',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=5, null=True, verbose_name='were the pathological signs in harmony with the clinical signs and laboratory reports?'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='num_of_species_affected',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number of species affected'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='prognosis',
            field=models.CharField(blank=True, choices=[('G', 'good'), ('F', 'fair'), ('P', 'poor')], default='G', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='sickness_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='duration of the sickness'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='species_affected',
            field=models.CharField(blank=True, choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20, null=True, verbose_name='animal species affected'),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='treatment_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='operation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Operation'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='operation_nature',
            field=models.CharField(blank=True, choices=[('C', 'c_section'), ('I', 'interstinal_torsion'), ('T', 'tumor_extraction'), ('C', 'canine_spaying'), ('H', 'hernia'), ('W', 'Warts_extraction'), ('C', 'castration'), ('S', 'skin_injuries'), ('F', 'fructure'), ('R', 'rumenatomy'), ('O', 'other')], default='C', max_length=20, null=True, verbose_name='Nature of operation'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='post_operation_management',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Post operation management'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='prognosis',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Prognosis'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='sex_of_the_animal',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], default='', max_length=20, null=True, verbose_name='Sex of the animal'),
        ),
        migrations.AlterField(
            model_name='surgical_approach_form',
            name='species_operated_on',
            field=models.CharField(blank=True, choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20, null=True, verbose_name='Animal species affected'),
        ),
        migrations.AlterField(
            model_name='vaccination_form',
            name='sex_of_the_animal',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], default='M', max_length=20, null=True, verbose_name='Sex of the animal'),
        ),
    ]
