# Generated by Django 3.1.3 on 2021-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_auto_20210322_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificial_insemination_form',
            name='time_of_heat_sign',
            field=models.TimeField(verbose_name='Time of heat sign'),
        ),
        migrations.AlterField(
            model_name='artificial_insemination_form',
            name='time_of_insemination',
            field=models.TimeField(verbose_name='Time of insemination'),
        ),
    ]
