# Generated by Django 3.1.3 on 2021-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_auto_20210203_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination_form',
            name='next_date_of_vaccination',
            field=models.DateField(verbose_name='Next date of vaccination'),
        ),
    ]
