# Generated by Django 3.1.3 on 2021-02-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_auto_20210203_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm_consultation',
            old_name='Dairy_cows',
            new_name='dairy_cows',
        ),
    ]
