# Generated by Django 3.1.3 on 2021-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_auto_20210203_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_consultation',
            name='by_veterinary_officer',
        ),
        migrations.AddField(
            model_name='farm_consultation',
            name='farm_manager',
            field=models.CharField(choices=[('V', 'Veterinary Officer'), ('L', 'Livestock Officer')], default='', max_length=20, verbose_name='Is the farm managed by a veterinary officer or livestock officer?'),
        ),
    ]
